name: Full Stack CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    # Backend
    - name: Install backend dependencies
      run: |
        cd backend
        npm install

    # Frontend
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    - name: Build frontend
      run: |
        cd frontend
        npm run build || echo "No build script"

    # Install Docker Compose (IMPORTANT FIX)
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    # Docker Build
    - name: Build Docker containers
      run: docker-compose build