name: Full Stack CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Backend setup
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install backend dependencies
      run: |
        cd backend
        npm install

    # Frontend setup
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    # Build frontend
    - name: Build frontend
      run: |
        cd frontend
        npm run build

    # Docker build
    - name: Build Docker containers
      run: docker-compose build